[Settings]
;Settings General settings for the Compose Key program.
;NOTE: You need to restart for the new settings to take effect.


ModifierKey=Right Ctrl
;ModifierKey Key used to trigger the 'Compose' function. Press this key, release, then press the two compose keys, one after the other.
;ModifierKey Type: DropDown Caps Lock|Right Winkey|Left Winkey|Right Alt|Left Alt|Right Ctrl|Left Ctrl|Right Shift|Left Shift|Insert|Num Lock|Escape|Tab
;ModifierKey Default: Right Ctrl

UseCapsLock=1
;UseCapsLock Also use the CapsLock key as a modifier. Press Shift+CapsLock (or Ctrl+CapsLock) to trigger normal CapsLock function.
;UseCapsLock Type: Checkbox
;UseCapsLock CheckboxName: Use CapsLock
;UseCapsLock Default: 1

SoundOnReset=1
;SoundOnReset Play a brief sound blip if the modifer key has been reset by pressing it twice.
;SoundOnReset Type: CheckBox
;SoundOnReset CheckboxName: Play sound
;SoundOnReset Default: 1

ResetDelay=2000
;ResetDelay Delay, in milliseconds, before reseting the modifier key, to avoid unwanted compose key entries.
;ResetDelay Type: Integer
;ResetDelay Default: 2000
